# Generated by Django 4.0.4 on 2022-05-12 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_entrenador_pokemon_remove_libro_editorial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='fecha_publicacion',
        ),
    ]
